### ISSUE TITLE
/lib/http/index.js var DEAULT_TIMEOUT value

### ISSUE THREAD

**Issue by Esowteric** [rqlite/rqlite-js#12]
Hi, line 39 of /lib/http/index.js reads:
`var DEAULT_TIMEOUT = 30;`
That's 30mS. Should it have been 30000 (for 30S)?

It's not a problem, as I'm setting httpOptions as per the readme's "Keep Alive Example" section, but it threw me for a while.

Thanks a lot,
Eric T.

**Comment by justinmorant** [comment]
@Esowteric thanks for pointing that out I will get it changed

**Comment by Esowteric** [comment]
Ah, thanks for that, Justin.
