### ISSUE TITLE
Clarifying question

### ISSUE THREAD

**Issue by euroclydon37** [rqlite/rqlite-js#15]
# A question about clusters
**rqlite** talks about writes having to go to the master node in a cluster. I was wondering how **rqlite-js** handles this? Does is automatically locate and communicate with the master node, or do I have to manually find the master node and use its address in the `connect` function?

**Comment by otoolep** [comment]
I'm not sure what reqlite-js does, but it can use the 301 returned by a non-leader node -- rqlite-js pulls the new URL from the `Location` HTTP header. This is what the rqlite CLI does:

https://github.com/rqlite/rqlite/blob/master/cmd/rqlite/main.go#L166

More detail about how a follower repsonds to query:

https://github.com/rqlite/rqlite/blob/master/DOC/DATA_API.md#sending-requests-to-followers

**Comment by euroclydon37** [comment]
Fantastic
