### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by jschlanger12** [rqlite/rqlite-js#16]
When connecting to a node to either create table, post, select, etc. if it is not the leader node it will throw an error. How in javascript do you get the redirect to the leader node or how can you find the leader node.

**Comment by justinmorant** [comment]
By default the HTTP client should follow up to 5 redirects, 300 level http
responses, so it should be automatic. Are you not experiencing that
behaviour?

**Comment by jschlanger12** [comment]
No, I am not getting the 300 level http responses. I am getting 400 and 405 errors. Is there any examples that you could provide or point me to as far as what to do in javascript/node. I need to be able to create a table, post to it, and get info from a table.

**Comment by otoolep** [comment]
If you're getting 400 or 405 it means exactly that. Your request is invalid, or you using the wrong HTTP methods. You need valid requests first, then the system will redirect if necessary.

I would check your code generating the requests.

**Comment by jschlanger12** [comment]
@otoolep How would you go about building the correct http method then? I think i just have a fundamental misunderstanding of how to do it since i am not too familiar with javascript/node.

**Comment by otoolep** [comment]
@jschlanger12 -- the API is fully documented here: https://github.com/rqlite/rqlite/blob/master/DOC/DATA_API.md

I'm not familiar with the JS implementation however, so am not sure if you're hitting a bug, or not using the JS library correctly.

**Comment by justinmorant** [comment]
@jschlanger12 a code example would help in further debugging your issue.  If you just need another example of how to use the library that is not covered in the README maybe the integration tests will be of some help.  https://github.com/rqlite/rqlite-js/blob/master/es6/api/data/client/test.integration.js

**Comment by RameshRM** [comment]
+1, any `db/execute` commands don't execute on a `follower` and only executes on `leader`; how are we supposed to handle this ? I am getting error thrown, cant follow the `redirection location` either. I am using simple `superagent` with `superagent.redirects(2)` , Is it safe to query `/status ` and follow the `leader` ?

**Comment by justinmorant** [comment]
@otoolep if the response from the server is 301 or 302 the superagent library should be redirecting automatically.  Is a 30X HTTP response code correct in this scenario or is there a 200 response that I need to parse and handle automatically with the rqlite-js client.  If I have a better understand of the server response codes plus any data that needs to be parse and how they are supposed to flow I can mock up a test and correct the issue.

@RameshRM what is HTTP request to `db/execute` and the response code plus body you are seeing?

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite/blob/master/DOC/DATA_API.md#example-of-redirect-on-query shows what is returned. This is what happens for `db/execute`, or `db/query` if weak or strong read consistency is selected.

**Comment by RameshRM** [comment]
@justinmorant I do see 301 / 302, The problem i ran in to is if my `http-adv-addr` or `join` address has a `http` prefix, the location header comes back with *`http://http://` I am not able to consistently reproduce this thou.

> Also I do see occasionally **405** for using `/db/execute` sometimes, I am guessing this could be related to wrong location header. 

Btw, my setup is not using `rqlite-js` I found it is too heavy for my `nodejs` setup, iam only using `Superagent`. 

The way i use is 

````
function doPost(url, body, callback){
require('superagent').post(url).redirects(0).end(function(err, response){

if(response.statusCode ===301){
    return doPost(url, body, callback);
}else{
return callback(err, response);
}
});

}
```

**Comment by otoolep** [comment]
HTTP 405 is "Method not allowed". My guess is you're using the wrong HTTP method -- or the code that does the redirect is not using the wrong method. A library might do a POST, receive a redirect, and then follow the location, but hit that location with a GET. Not saying that is what is happening here, but in the Go CLI code, redirects are handled manually: https://github.com/rqlite/rqlite/blob/master/cmd/rqlite/main.go#L186

**Comment by RameshRM** [comment]
@otoolep I understand, I need to find a stable way to reproduce, I saw the error few times, trying to find a consistent way to reproduce. I think it has to do with `http` prefix with either `join | httpadv-adr`

**Comment by justinmorant** [comment]
@RameshRM the RQLiteJS library has been rewritten from the ground up with v1 and one of the features which was added was 301 redirect handling.  The new implementation is much faster and only works in NodeJS (previously it was also designed to run in the browser).  Feel free to read through the README example first to see what has change since you now need to instantiate a class.
