### ISSUE TITLE
Knex client driver

### ISSUE THREAD

**Issue by katywings** [rqlite/rqlite-js#17]
I am thinking about creating a [knex](http://knexjs.org/) based driver. Is this something you would be interested in adding to the rqlite org?

**Comment by otoolep** [comment]
Sure, I would accept one and create a repo within the org for it.

**Comment by otoolep** [comment]
I suggest you do some initial work within your own org to show us what you have in mind, and then I could create the repo, and give you commit rights to it.

**Comment by katywings** [comment]
@otoolep Sounds good 👌

**Comment by katywings** [comment]
So to give you a little update: I created a repository with an org name.

The dialect already supports the core surface of the knex api but there is of course room for improvement.

---

One little thing that might interest you: [src](https://github.com/lufrai/knex-rqlite/blob/master/lib/back/rqliteDialect.ts#L30)
I figured out that rqlite-js for empty sql results returns `[{}]` instead of `[]` when using `toArray()` :)

---

Links to knex-rqlite:
- npm: https://www.npmjs.com/package/@lufrai/knex-rqlite
- repo: https://github.com/lufrai/knex-rqlite

**Comment by otoolep** [comment]
Thanks for this. Are you interested in moving this to a repo in the rqlite org? I.e. rqlite/knex-rqlite. I would give you full commit rights to that repo. Whatever you like.

**Comment by otoolep** [comment]
That way it becomes the "official" knex driver.

**Comment by katywings** [comment]
Sure, I like that approach 🙂

**Comment by otoolep** [comment]
OK, repo created and you have commit access. You should also be able to merge pull requests opened by others, configure the repo to a certain extent, etc.

https://github.com/rqlite/knex-rqlite

So feel free to drop your code in there, and invite others to add patches.

**Comment by katywings** [comment]
Nice! Thanks for the quick setup 💪

I'll probably have time on wednesday or at the weekend ^^

**Comment by katywings** [comment]
@otoolep I added the code to https://github.com/rqlite/knex-rqlite, updated the npm/pkg related configs, rebuilt and published to npm. You also should've gotten an invite for the npm package ;).

**Comment by otoolep** [comment]
Great, thank you for your contribution.
