### ISSUE TITLE
Cannot find module '@babel/runtime/helpers/interopRequireDefault'

### ISSUE THREAD

**Issue by littleli** [rqlite/rqlite-js#21]
I have encountered above error when attempting to work with a module from [nbb](https://github.com/babashka/nbb).

I don't know why you need to depend on this but I know you already have a great a fully working es6 codebase.

My request is, if possible, to move completely to es6 without the interop part, or put an interop aside as an workaround.

**Comment by borkdude** [comment]
A pure JS repro:

foo.mjs:
```
import * as foo from 'rqlite-js'
```

```
$ node foo.mjs
internal/modules/cjs/loader.js:902
  const err = new Error(message);
              ^

Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
```

**Comment by justinmorant** [comment]
@borkdude there is a pure ES6 implementation in the es6 folder if you would prefer to use this an see if it works.  The NPM module is transpiled to ES5 from ES6.  Could you first try importing just the exports you need from `'rqlite-js` and not `*`?

Explicit import:
`import { DataApiClient, BackupApiClient, BackupApiClient  } from 'rqlite-js/es6'`

ES Import:
`import * as foo from 'rqlite-js/es6'`

Are you using babel in your project?  Sometimes this error can occur when babel versions conflict.

**Comment by borkdude** [comment]
@justinmorant 

```
import * as foo from 'rqlite-js/es6'
```

does not work as the files in the `es6` modules are not named `.mjs` and you may not use import on `.js` files if package.json does not have `"type": "module"` or the JS files should use `.mjs`. Have you tried using the es6 module yourself in Node.js?

**Comment by borkdude** [comment]
Example:

foo.mjs
```
import { DataApiClient, BackupApiClient } from 'rqlite-js/es6/index.js'
```
gives:
```
file:///private/tmp/rq/foo.mjs:1
import { DataApiClient, BackupApiClient } from 'rqlite-js/es6/index.js'
         ^^^^^^^^^^^^^
SyntaxError: Named export 'DataApiClient' not found. The requested module 'rqlite-js/es6/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'rqlite-js/es6/index.js';
const { DataApiClient, BackupApiClient } = pkg;
```

**Comment by borkdude** [comment]
And this:

foo.mjs
``` 
import * as foo from 'rqlite-js/es6/index.js'
```

```
$ node foo.mjs
(node:61458) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/private/tmp/rq/node_modules/rqlite-js/es6/index.js:5
import DataApiClient from './api/data'
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by justinmorant** [comment]
@borkdude the testing framework uses ES6 in docker containers to run tests before the npm lib is built.  The container use babel to execute the Javascript so it does not throw these errors.  I will find sometime to convert the ES6 code to .mjs to see if I can remove babel.

In the meantime if you change from using `import *` to named imports i.e. `import { DataApiClient, BackupApiClient } from 'rqlite-js'` (notice the es6 folder was exclude) does this work for you?

**Comment by borkdude** [comment]
>  does this work for you?

No

**Comment by justinmorant** [comment]
The work has begun on mjs branch with es6 implemented using the `.mjs` extension.  It is working transpiling from es6 to es5, but rewriting the import `.mjs.` to require `.js` is not correctly replacing the file extensions.

Once this is sorted out I will update the thread.

**Comment by littleli** [comment]
> @borkdude and @littleli jqlite-js v2.5.5 has been released with an updated package.json, @babel/runtime was moved from dev dependencies to dependencies which should fix the interop issue.
> 
> The expectation is the import * should no longer throw an interop issue since the babel runtime is now a regular dependency.
> 
> `import * as foo from 'rqlite-js'`

This is output I get from shell

On es6 import:
```js
ᐅ node rq.js
(node:13785) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/littleli/Work/nbb/examples/rqlite/rq.js:1
import * as rq from 'rqlite-js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

On commonjs use:
```js
ᐅ node
Welcome to Node.js v18.0.0.
Type ".help" for more information.
> const rq = require('rqlite-js');
undefined
> rq
{
  DataApiClient: [class DataApiClient extends ApiClient],
  BackupApiClient: [class BackupApiClient extends HttpRequest],
  StatusApiClient: [class StatusApiClient extends ApiClient]
}
```

so definitely `require` (commonjs) module works now!

For my original use case it means `nbb` is able to load the module as well. FYI example similar to one from README in the project.

```clojure
(ns example
  (:require ["rqlite-js$default" :as rq]
            [promesa.core :as p]))

(def client (rq/DataApiClient. "http://localhost:4001"))

(defn query-by-name [name]
  (str "SELECT id FROM foo WHERE name = \"" name "\""))

(p/let [results (.query client (query-by-name "fiona"))]
  (when-not (.hasError results)
    (-> results
        (.get 0)
        (.get "id")
        (prn))))

;; Output
1
#<Promise[~]>
```

I hope the `.mjs` improvement will make it even better and future proof! Great library Justin!

**Comment by littleli** [comment]
Ok, one more update. After renamed `rq.js` to `rq.mjs` es6 import seems to work too. So I think we're good.

**Comment by justinmorant** [comment]
@littleli thanks for confirming it is now working. This issue is closed.
