### ISSUE TITLE
Any handling of HTTP 301 from follower?

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite-js#9]
@justinmorant -- does this software do anything special if it gets HTTP 301 back from a node? I.e. dealing with the following?

https://github.com/rqlite/rqlite/blob/master/doc/DATA_API.md#sending-requests-to-followers

**Comment by justinmorant** [comment]
@otoolep superagent is the base HTTP client library and it follows 301 redirects by default.  http://visionmedia.github.io/superagent/#following-redirects

**Comment by otoolep** [comment]
Got it, this tells me what I need to know.
